# ================================================
# Variables
# ================================================

@nextApiUrl = http://localhost:7733/api

### ==============================================
# User | Create account by email:pass
# ================================================

POST {{nextApiUrl}}/users
Content-Type: application/json
{
  "email": "mando@gmail.com",
  "password": "password123!",
  "username": "Mandolorian"
}

### ==============================================
# User | Login by email:pass
# ================================================

POST {{nextApiUrl}}/users/login
Content-Type: application/json
{
  "email": "grogu@gmail.com",
  "password": "password123!"
}

### ==============================================
# User | Get info
# ================================================


GET {{nextApiUrl}}/users/me
Content-Type: application/json
Cookie: authjs.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiVjVIOVJVaWNRekZmel9tTG53MWRIdkQ4VEZHSUVwMVh4eExTR0hUNDlySm50MDlPWER1QUx1RWk5LXFaN1FjYmg1UHhkdlFzYTVKcHl5Ymh3QmM4cncifQ..Ij0Jwjg0SNVThbaYQBll2Q.x8xQG0GDR24d-30v60Yvn0PS8xB83ALxvq9e6Wjd09wWdYv5A_UFj50VWfB2nyWJNWpM1NNDnDf36AJ-SIFcfQYhO-FPYDqJuAGiXR7xkOp5P5zjfWsBtcYus7B9sKjxOySqun5jJgRjUFlfdmNM0EeQwhahnZA1UF3P7F7gYxUdAwNNho7oIdAzfKl5pVX4UJlEmXIQIq1WzDiyKOegTtUL_1Q_73ihE1jLEZ8KCH4.x4vC7VU7AqWl-bCpZgsF_zNFZxH8UMPdDJgqM2KCW8A
#Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiVjVIOVJVaWNRekZmel9tTG53MWRIdkQ4VEZHSUVwMVh4eExTR0hUNDlySm50MDlPWER1QUx1RWk5LXFaN1FjYmg1UHhkdlFzYTVKcHl5Ymh3QmM4cncifQ..YvAhcAXk33nSk5yM_wLegA.G4hi9yUKMptH42H-rDgWs2zLbzrTPCnY5Acb9p1siEBdrcL5vFMlZabA9SUdd2JX5vQgCP6XMJ5OX4omS6VxRepzmJwHNnQE06s3A7VdmBR99muzVuDhO8C9GEKQMHmY5eNHB9eB5m_32GiYcgnM3dFkXpkulQNWLGab5FFI_dSNYm68ld_ualUes0WzemlGzfI3mfre6gY1PUctgQQyBmiR7HrMP9UDB_qDWOSrTbQ.Pv2brSg6PkdgEavd8au3KM22gMOeSLjzcfWAnk0v1Us 



### ==============================================
# User | Change data
# ================================================

PATCH {{nextApiUrl}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNzVmZGVlYWQtYmM3Zi00NTVmLTgyZGYtZGE0NWQzOWRjZDdhIiwiZXhwIjoxNzIwNzcwNDA3LCJpYXQiOjE3MTI5OTQ0MDd9.Ebj0r0CFWCHqzmnc07Tk2HN4wo1ALNDgq_ImDbrDRWs
{
  "new_email": "john@gmail.com",
  "new_password": "password123!",
  "new_subscriptions": ["ea12cd10-be78-49f6-b10a-0e1640b8e40f", "9d0aee7c-9bb9-450c-b073-28c91289ec8a"]
}



